### ISSUE TITLE
..

### ISSUE THREAD

**Issue by flexbarker** [DARIAH-ERIC/nerd-wp#5]
https://nerdsfun.de/mit-lendstar-geht-es-als-teil-der-epay-familie-weiter/

Howdie, can you say how we can use it? 
Can not use. No NerdInstance?
;)

**Comment by laurentromary** [comment]
The reference instance is the one hosted as a service at huma-num: http://nerd.huma-num.fr

**Comment by yoannspace** [comment]
Thanks @laurentromary!
@flexbarker if you do decide to use this instance, please note that the full service URL to mention in the plugin is `http://nerd.huma-num.fr/nerd/`

**Comment by yoannspace** [comment]
Please see the README as it is now stated in there
